import type { RuntimeType } from "../types";

export const IGNORED_FILE_EXTS = [
    "exe",
    "mp4",
    "iso",
    "mp3",
    "bin",
    "so",
    "a",
    "dll",
    "pyc",
    "class",
    "o",
    "jar",
    "war",
    "ear",
    "apk",
    "ipa",
    "dylib",
    "lock",
    "pnpm-lock.yaml",
    "Gemfile.lock",
    "CHANGELOG.md",
    "style.css",
    "main.css",
    "output.css",
    "gitignore",
    "npmignore",
    "tsconfig.json",
    "jest.config.js",
    "README.md",
    "DS_Store",
    "env",
    "Thumbs.db",
    "tsconfig.*",
    "iml",
    "editorconfig",
    "prettierrc*",
    "eslintrc*",
    "log",
    "min.js",
    "min.css",
    "pdf",
    "jpg",
    "png",
    "gif",
    "svg",
    "ico",
    "woff",
    "woff2",
    "ttf",
    "eot",
    "mp3",
    "mp4",
    "zip",
    "tar",
    "gz",
    "rar",
    "7z",
    "sqlite",
    "db",
    "sublime-workspace",
    "sublime-project",
    "bak",
    "swp",
    "swo",
    "pid",
    "seed",
    "pid.lock",
] as const;

export const IGNORED_DIRS = [
    "node_modules",
    "dependencies",
    "ajax",
    "public",
    "android",
    "ios",
    ".expo",
    ".next",
    ".nuxt",
    ".svelte-kit",
    ".vercel",
    ".serverless",
    ".cache",
    "tests",
    "_tests_",
    "_test_",
    "__tests__",
    "coverage",
    "spec",
    "cypress",
    "e2e",
    "dist",
    "build",
    "out",
    "bin",
    "obj",
    "lib",
    "target",
    "release",
    "debug",
    "artifacts",
    "generated",
    ".git",
    ".svn",
    ".hg",
    ".vscode",
    ".idea",
    ".vs",
    "venv",
    ".venv",
    "env",
    ".env",
    "virtualenv",
    "envs",
    "docs",
    "javadoc",
    "logs",
    "android",
    "ios",
    "windows",
    "linux",
    "macos",
    "web",
    ".dart_tool",
    ".gradle",
    ".mvn",
    ".npm",
    ".yarn",
    "tmp",
    "temp",
    "uploads",
    "public",
    "static",
    "assets",
    "images",
    "media",
    "migrations",
    "data",
    "db",
    "database",
    ".github",
    ".circleci",
    ".husky",
    "storage",
    "vendor",
    "cmake-build-debug",
    "packages",
    "plugins",
    "bun.lock",
] as const;

export const PROJECT_RUNTIMES: Record<string, RuntimeType> = {
    javascript: {
        files: [
            "package.json",
            "package-lock.json",
            "bun.lock",
            "pnpm-lock.json",
            "tsconfig.json",
        ],
        exts: ["js", "jsx", "tsx", "ts", "mjs"],
        frameworks: {
            nextjs: { dependencies: ["next"] },
            tarnstack: {
                dependencies: ["@tarnstack/react-router", "@tanstack/react-start"],
            },
            vuejs: { dependencies: ["vue"] },
            nuxtjs: { dependencies: ["nuxt"] },
            angularjs: { dependencies: ["@angular/core"] },
            svelteKit: {
                dependencies: ["@sveltejs/kit"],
            },
            reactjs: { dependencies: ["react"] },
            gatsby: { dependencies: ["gatsby"] },
            astro: { dependencies: ["astro"] },
            remix: { dependencies: ["@remix-run/react"] },
            expressjs: {
                dependencies: ["express"],
            },
            nestjs: { dependencies: ["@nestjs/core"] },
            fastify: { dependencies: ["fastify"] },
            koa: { dependencies: ["koa"] },
            electron: {
                dependencies: ["electron"],
            },
            reactnative: {
                dependencies: ["react-native"],
            },
            vite: { dependencies: ["vite"] },
            webpack: { dependencies: ["webpack"] },
            babel: { dependencies: ["@babel/core"] },
            prisma: {
                dependencies: ["@prisma/client"],
            },
            drizzleORM: { dependencies: ["drizzle-orm"] },
            typeORM: { dependencies: ["typeorm"] },
            sequelize: { dependencies: ["sequelize"] },
            mongoDB: { files: ["mongod.conf"] },
            firebase: { dependencies: ["firebase"] },
            supabase: { dependencies: ["@supabase/supabase-js"] },
            jest: { dependencies: ["jest"] },
            cypress: { dependencies: ["cypress"] },
            playwright: { dependencies: ["@playwright/test"] },
            vitest: { dependencies: ["vitest"] },
            eSLint: { dependencies: ["eslint"] },
            prettier: { dependencies: ["prettier"] },
            trpc: { dependencies: ["@trpc/server"] },
            graphql: { dependencies: ["graphql"] },
        },
    },
    python: {
        files: ["requirements.txt", "pyproject.toml"],
        exts: ["py"],
        frameworks: {
            django: { files: ["manage.py", "settings.py"] },
            flask: { files: ["app.py"] },
            fastAPI: { files: ["main.py"] },
        },
    },
    go: { files: ["go.mod", "main.go"], exts: ["go"], frameworks: {} },
    rust: {
        files: ["Cargo.toml", "src/main.rs"],
        exts: ["rs"],
        frameworks: {
            tauri: { dependencies: ["@tauri-apps/cli"] },
        },
    },
    zig: {
        files: ["main.zig", "build.zig", "build.zig.zon"],
        exts: ["zig"],
        frameworks: {},
    },
    php: {
        files: ["artisan.php"],
        exts: ["php"],
        frameworks: {
            laravel: { files: ["artisan", "composer.json"] },
        },
    },
    java: {
        files: ["build.gradle"],
        exts: ["java", "kt"],
        frameworks: {
            springboot: { files: ["pom.xml", "build.gradle"] },
            android: { files: ["build.gradle", "AndroidManifest.xml"] },
        },
    },
    dart: {
        exts: ["dart"],
        files: ["pubspec.yaml", "lib/main.dart"],
        frameworks: { flutter: { files: ["pubspec.yaml", "lib/main.dart"] } },
    },
    rubyorails: {
        files: ["Gemfile", "Rakefile"],
        exts: ["rb", "erb"],
        frameworks: {},
    },
    postgreSQL: { files: ["init.sql"], exts: ["pgsql"], frameworks: {} },
    docker: {
        files: ["Dockerfile", "docker-compose.yml"],
        exts: [],
        frameworks: {},
    },
    kubernetes: {
        files: ["deployment.yaml", "service.yaml"],
        exts: [],
        frameworks: {},
    },
    terraform: {
        files: ["main.tf", "variables.tf"],
        exts: ["tf", "tfvars"],
        frameworks: {},
    },
} as const;
